// Quiz express : alternative aux énigmes du jour pour ceux qui n'ont pas le temps ou pas l'envie.
// 5 questions de culture générale en 3 thèmes, 15 secondes chacune, 4 choix ; 3 bonnes réponses
// débloquent le bonus du jour. Chaque joueur a sa propre série, sans répétition dans une saison.
// Format d'une question : [énoncé, bonne réponse, leurre, leurre, leurre].
import { makeRng } from '../engine/rng.js';

export const QUIZ = { questions: 5, secondes: 15, seuil: 3 };

export const QUIZ_THEMES = {
  monde: { nom: 'Monde', sous: 'histoire, géo, arts', ico: '🌍' },
  sciences: { nom: 'Sciences', sous: 'nature, corps, espace', ico: '🔬' },
  belgique: { nom: 'Belgique', sous: 'pays, police, culture', ico: '🇧🇪' },
};

export const QUIZ_BANQUE = {
  monde: [
    ['Quelle est la capitale de l’Australie ?', 'Canberra', 'Sydney', 'Melbourne', 'Perth'],
    ['Quel est le plus long fleuve d’Europe ?', 'La Volga', 'Le Danube', 'Le Rhin', 'Le Dniepr'],
    ['Qui a peint « La Liberté guidant le peuple » ?', 'Eugène Delacroix', 'Théodore Géricault', 'Jacques-Louis David', 'Gustave Courbet'],
    ['Quel traité a créé l’Union européenne ?', 'Maastricht', 'Rome', 'Lisbonne', 'Nice'],
    ['En quelle année le mur de Berlin est-il tombé ?', '1989', '1987', '1991', '1985'],
    ['Qui a écrit « Les Misérables » ?', 'Victor Hugo', 'Émile Zola', 'Honoré de Balzac', 'Alexandre Dumas'],
    ['Quelle est la capitale du Canada ?', 'Ottawa', 'Toronto', 'Montréal', 'Vancouver'],
    ['Quel est le plus haut sommet d’Afrique ?', 'Le Kilimandjaro', 'Le mont Kenya', 'Le mont Stanley', 'Le Toubkal'],
    ['Quel pays a la plus grande superficie ?', 'La Russie', 'Le Canada', 'La Chine', 'Les États-Unis'],
    ['Qui a peint « La Jeune Fille à la perle » ?', 'Johannes Vermeer', 'Rembrandt', 'Jan Van Eyck', 'Frans Hals'],
    ['Quel empereur romain a fait bâtir un mur dans le nord de l’Angleterre ?', 'Hadrien', 'Trajan', 'Auguste', 'Néron'],
    ['Qui fut la première femme à recevoir un prix Nobel ?', 'Marie Curie', 'Bertha von Suttner', 'Irène Joliot-Curie', 'Selma Lagerlöf'],
    ['En quelle année Christophe Colomb a-t-il atteint l’Amérique ?', '1492', '1498', '1488', '1504'],
    ['Quelle est la capitale de la Turquie ?', 'Ankara', 'Istanbul', 'Izmir', 'Bursa'],
    ['Qui a composé « Les Quatre Saisons » ?', 'Antonio Vivaldi', 'Jean-Sébastien Bach', 'Georg Friedrich Haendel', 'Arcangelo Corelli'],
    ['Nairobi est la capitale de quel pays ?', 'Le Kenya', 'La Tanzanie', 'L’Ouganda', 'L’Éthiopie'],
    ['Dans quelle ville se trouve la Sagrada Família ?', 'Barcelone', 'Madrid', 'Séville', 'Valence'],
    ['Qui a écrit « 1984 » ?', 'George Orwell', 'Aldous Huxley', 'Ray Bradbury', 'H. G. Wells'],
    ['Dans quel pays se trouve le Machu Picchu ?', 'Le Pérou', 'La Bolivie', 'L’Équateur', 'Le Chili'],
    ['Quel détroit sépare l’Europe de l’Afrique ?', 'Gibraltar', 'Le Bosphore', 'Messine', 'Ormuz'],
    ['Qui fut le premier président de la Ve République française ?', 'Charles de Gaulle', 'Georges Pompidou', 'René Coty', 'François Mitterrand'],
    ['Quelle est la capitale de la Nouvelle-Zélande ?', 'Wellington', 'Auckland', 'Christchurch', 'Dunedin'],
    ['Quel peintre s’est tranché l’oreille en 1888 ?', 'Vincent van Gogh', 'Paul Gauguin', 'Edvard Munch', 'Henri de Toulouse-Lautrec'],
    ['Qui a sculpté « Le Penseur » ?', 'Auguste Rodin', 'Camille Claudel', 'Michel-Ange', 'Aristide Maillol'],
    ['Quel est le plus grand désert chaud du monde ?', 'Le Sahara', 'Le Kalahari', 'Le désert d’Arabie', 'Le Namib'],
    ['Quelle est la capitale du Brésil ?', 'Brasília', 'Rio de Janeiro', 'São Paulo', 'Salvador'],
    ['Quel pays a offert la statue de la Liberté aux États-Unis ?', 'La France', 'Le Royaume-Uni', 'L’Italie', 'L’Espagne'],
    ['Qui a écrit « Le Comte de Monte-Cristo » ?', 'Alexandre Dumas', 'Victor Hugo', 'Jules Verne', 'Eugène Sue'],
    ['Quelle ville s’est appelée Byzance, puis Constantinople ?', 'Istanbul', 'Athènes', 'Alexandrie', 'Antioche'],
    ['Qui a peint le plafond de la chapelle Sixtine ?', 'Michel-Ange', 'Raphaël', 'Léonard de Vinci', 'Sandro Botticelli'],
    ['Quel fleuve traverse Bagdad ?', 'Le Tigre', 'L’Euphrate', 'Le Nil', 'Le Jourdain'],
    ['Quelle est la monnaie du Japon ?', 'Le yen', 'Le won', 'Le yuan', 'Le ringgit'],
    ['En quelle année l’homme a-t-il marché sur la Lune pour la première fois ?', '1969', '1967', '1971', '1965'],
    ['Qui a écrit « Don Quichotte » ?', 'Miguel de Cervantes', 'Lope de Vega', 'Pedro Calderón', 'Francisco de Quevedo'],
    ['Quelle est la capitale du Maroc ?', 'Rabat', 'Casablanca', 'Marrakech', 'Fès'],
    ['Quel est le plus long fleuve d’Afrique ?', 'Le Nil', 'Le Congo', 'Le Niger', 'Le Zambèze'],
    ['Quel souverain a régné le plus longtemps sur le Royaume-Uni ?', 'Élisabeth II', 'Victoria', 'George III', 'Anne'],
    ['À quelle divinité le Parthénon d’Athènes est-il dédié ?', 'Athéna', 'Zeus', 'Apollon', 'Poséidon'],
    ['Qui a peint « Le Cri » ?', 'Edvard Munch', 'Gustav Klimt', 'Egon Schiele', 'Vassily Kandinsky'],
    ['Quelle est la capitale de l’Islande ?', 'Reykjavik', 'Oslo', 'Helsinki', 'Tórshavn'],
    ['Quel navigateur a mené l’expédition qui a réalisé le premier tour du monde ?', 'Fernand de Magellan', 'Vasco de Gama', 'James Cook', 'Francis Drake'],
    ['Quel compositeur était sourd à la fin de sa vie ?', 'Ludwig van Beethoven', 'Wolfgang Amadeus Mozart', 'Frédéric Chopin', 'Franz Schubert'],
    ['Dans quel pays se trouve Tombouctou ?', 'Le Mali', 'Le Niger', 'La Mauritanie', 'Le Burkina Faso'],
    ['Qui a écrit « L’Étranger » ?', 'Albert Camus', 'Jean-Paul Sartre', 'André Malraux', 'André Gide'],
    ['Quelle mer borde Venise ?', 'L’Adriatique', 'La Tyrrhénienne', 'La mer Ionienne', 'La mer Ligure'],
    ['Quel architecte a conçu la pyramide du Louvre ?', 'Ieoh Ming Pei', 'Jean Nouvel', 'Renzo Piano', 'Frank Gehry'],
    ['Quelle est la plus grande île du monde ?', 'Le Groenland', 'La Nouvelle-Guinée', 'Bornéo', 'Madagascar'],
    ['Qui a fondé l’Empire mongol ?', 'Gengis Khan', 'Kubilaï Khan', 'Tamerlan', 'Attila'],
    ['Dans quelle ville se trouve le siège de l’ONU ?', 'New York', 'Genève', 'Washington', 'Vienne'],
    ['Quel pays a le plus d’habitants aujourd’hui ?', 'L’Inde', 'La Chine', 'Les États-Unis', 'L’Indonésie'],
    ['Qui a écrit « Roméo et Juliette » ?', 'William Shakespeare', 'Christopher Marlowe', 'Molière', 'Lope de Vega'],
    ['Quelle chaîne de montagnes sépare l’Europe de l’Asie ?', 'L’Oural', 'Le Caucase', 'Les Carpates', 'L’Altaï'],
    ['Quel pharaon a vu son tombeau découvert presque intact en 1922 ?', 'Toutânkhamon', 'Ramsès II', 'Khéops', 'Akhenaton'],
    ['Quelle est la capitale de l’Argentine ?', 'Buenos Aires', 'Santiago', 'Montevideo', 'Córdoba'],
    ['Qui a peint « Les Nymphéas » ?', 'Claude Monet', 'Auguste Renoir', 'Édouard Manet', 'Paul Cézanne'],
  ],
  sciences: [
    ['Quel élément chimique a pour symbole « W » ?', 'Le tungstène', 'L’argent', 'Le tellure', 'Le vanadium'],
    ['Sur quelle planète une journée dure-t-elle plus longtemps qu’une année ?', 'Vénus', 'Mercure', 'Mars', 'Neptune'],
    ['Combien d’os compte le squelette d’un adulte ?', '206', '186', '226', '246'],
    ['Quel organe produit l’insuline ?', 'Le pancréas', 'Le foie', 'La rate', 'La thyroïde'],
    ['Quelle est, environ, la vitesse de la lumière dans le vide ?', '300 000 km/s', '30 000 km/s', '3 000 000 km/s', '150 000 km/s'],
    ['Quel gaz est le plus abondant dans l’air que nous respirons ?', 'L’azote', 'L’oxygène', 'L’argon', 'Le dioxyde de carbone'],
    ['Quel est le symbole chimique du sodium ?', 'Na', 'So', 'Sd', 'S'],
    ['Combien de chromosomes compte une cellule humaine ordinaire ?', '46', '44', '48', '23'],
    ['Qui a découvert la pénicilline ?', 'Alexander Fleming', 'Louis Pasteur', 'Robert Koch', 'Edward Jenner'],
    ['À combien de degrés Fahrenheit l’eau bout-elle au niveau de la mer ?', '212 °F', '180 °F', '200 °F', '232 °F'],
    ['Quel est le plus grand animal vivant ?', 'La baleine bleue', 'Le cachalot', 'L’éléphant d’Afrique', 'Le requin-baleine'],
    ['Combien de cœurs a une pieuvre ?', '3', '1', '2', '4'],
    ['Que signifie le sigle ADN ?', 'Acide désoxyribonucléique', 'Acide diribonucléique', 'Acide dinucléotidique', 'Acide désaminonucléique'],
    ['Dans quelle unité mesure-t-on une résistance électrique ?', 'L’ohm', 'Le volt', 'L’ampère', 'Le watt'],
    ['Quel métal est liquide à température ambiante ?', 'Le mercure', 'Le plomb', 'L’étain', 'Le zinc'],
    ['Combien de temps met la lumière du Soleil pour atteindre la Terre ?', 'Environ 8 minutes', 'Environ 8 secondes', 'Environ 1 heure', 'Environ 8 heures'],
    ['Que transporte principalement l’hémoglobine ?', 'L’oxygène', 'Le glucose', 'Le calcium', 'Les graisses'],
    ['Quel est l’animal terrestre le plus rapide ?', 'Le guépard', 'Le cheval', 'Le lion', 'Le lévrier'],
    ['Combien de dents compte la dentition complète d’un adulte ?', '32', '28', '30', '36'],
    ['Quelle est la formule de l’eau oxygénée ?', 'H₂O₂', 'H₂O', 'HO₂', 'H₃O'],
    ['Quel est le plus grand organe du corps humain ?', 'La peau', 'Le foie', 'Les poumons', 'Le cerveau'],
    ['Qui a établi le tableau périodique des éléments ?', 'Dmitri Mendeleïev', 'Antoine Lavoisier', 'John Dalton', 'Niels Bohr'],
    ['À combien de kelvins (environ) l’eau gèle-t-elle ?', '273 K', '0 K', '100 K', '373 K'],
    ['Sur quelle planète se trouve Olympus Mons, le plus grand volcan connu ?', 'Mars', 'Vénus', 'Jupiter', 'Mercure'],
    ['Quel vaisseau sanguin ramène le sang vers le cœur ?', 'La veine', 'L’artère', 'Le capillaire', 'L’aorte'],
    ['Quel élément a pour symbole « Fe » ?', 'Le fer', 'Le fluor', 'Le fermium', 'Le francium'],
    ['Quel est le symbole chimique de l’or ?', 'Au', 'Or', 'Ag', 'Go'],
    ['Quel est le symbole chimique du potassium ?', 'K', 'P', 'Po', 'Pt'],
    ['Quel organe filtre le sang pour produire l’urine ?', 'Le rein', 'Le foie', 'La vessie', 'La rate'],
    ['Quelle est, environ, la vitesse du son dans l’air ?', '340 m/s', '34 m/s', '3 400 m/s', '1 200 m/s'],
    ['Combien de lunes compte Mars ?', '2', '0', '1', '4'],
    ['Où se trouve le plus petit os du corps humain ?', 'Dans l’oreille', 'Dans le pied', 'Dans la main', 'Dans le nez'],
    ['Qui a découvert la radioactivité naturelle, en 1896 ?', 'Henri Becquerel', 'Marie Curie', 'Ernest Rutherford', 'Wilhelm Röntgen'],
    ['Qui a découvert les rayons X ?', 'Wilhelm Röntgen', 'Henri Becquerel', 'Pierre Curie', 'Nikola Tesla'],
    ['Quel est l’animal terrestre le plus lourd ?', 'L’éléphant d’Afrique', 'L’hippopotame', 'Le rhinocéros blanc', 'La girafe'],
    ['Combien de litres de sang (environ) circulent dans le corps d’un adulte ?', '5 litres', '2 litres', '8 litres', '12 litres'],
    ['Combien de côtés a un dodécagone ?', '12', '10', '20', '14'],
    ['Quelle est la racine carrée de 169 ?', '13', '12', '14', '17'],
    ['Qui a énoncé la loi de la gravitation universelle ?', 'Isaac Newton', 'Galilée', 'Johannes Kepler', 'Nicolas Copernic'],
    ['Dans quelle unité mesure-t-on une fréquence ?', 'Le hertz', 'Le joule', 'Le newton', 'Le pascal'],
    ['Quelle est l’étoile la plus proche de la Terre ?', 'Le Soleil', 'Proxima du Centaure', 'Sirius', 'L’étoile Polaire'],
    ['Combien de vertèbres cervicales a l’être humain ?', '7', '5', '9', '12'],
    ['Quel oiseau pond les plus gros œufs ?', 'L’autruche', 'L’émeu', 'Le casoar', 'L’albatros'],
    ['Quel métal est le meilleur conducteur d’électricité ?', 'L’argent', 'Le cuivre', 'L’or', 'L’aluminium'],
    ['De quoi le diamant est-il composé ?', 'De carbone', 'De silicium', 'De quartz', 'De bore'],
    ['Combien de paires de côtes a l’être humain ?', '12', '10', '11', '14'],
    ['Dans quelle couche de l’atmosphère se trouve la couche d’ozone ?', 'La stratosphère', 'La troposphère', 'La mésosphère', 'La thermosphère'],
    ['Quel âge a l’Univers, environ ?', '13,8 milliards d’années', '4,5 milliards d’années', '100 milliards d’années', '1 milliard d’années'],
    ['Quel âge a la Terre, environ ?', '4,5 milliards d’années', '13,8 milliards d’années', '450 millions d’années', '1,2 milliard d’années'],
    ['Quelle planète a les anneaux les plus visibles ?', 'Saturne', 'Jupiter', 'Uranus', 'Neptune'],
    ['Quel est le gaz rejeté par les plantes lors de la photosynthèse ?', 'L’oxygène', 'L’azote', 'Le dioxyde de carbone', 'Le méthane'],
    ['Quelle partie de l’œil donne sa couleur aux yeux ?', 'L’iris', 'La pupille', 'La rétine', 'La cornée'],
    ['Combien de pattes a une araignée ?', '8', '6', '10', '12'],
    ['Quel savant a formulé la théorie de l’évolution par la sélection naturelle ?', 'Charles Darwin', 'Jean-Baptiste de Lamarck', 'Gregor Mendel', 'Georges Cuvier'],
  ],
  belgique: [
    ['Qui a inventé le saxophone ?', 'Adolphe Sax', 'Toots Thielemans', 'Django Reinhardt', 'César Franck'],
    ['Quel est le vrai nom d’Hergé ?', 'Georges Remi', 'Georges Rémy', 'Henri Gérard', 'Hervé Georges'],
    ['Quelle ville belge est surnommée « la Cité ardente » ?', 'Liège', 'Charleroi', 'Namur', 'Verviers'],
    ['Depuis quelle année la Constitution dit-elle que « la Belgique est un État fédéral » ?', '1993', '1970', '1980', '2001'],
    ['Quelle loi a organisé la police intégrée, structurée à deux niveaux ?', 'Loi du 7 décembre 1998', 'Loi du 5 août 1992', 'Loi du 26 avril 2002', 'Loi du 15 mai 2007'],
    ['Quel inventeur belge a mis au point la dynamo industrielle ?', 'Zénobe Gramme', 'Ernest Solvay', 'Adolphe Sax', 'Lieven Gevaert'],
    ['Combien de provinces compte la Belgique ?', '10', '9', '11', '12'],
    ['Qui fut le premier roi des Belges ?', 'Léopold Ier', 'Albert Ier', 'Léopold II', 'Guillaume Ier'],
    ['En quelle année la Belgique a-t-elle proclamé son indépendance ?', '1830', '1815', '1831', '1848'],
    ['Quel est le point culminant de la Belgique ?', 'Le signal de Botrange', 'La Baraque Michel', 'Le mont Rigi', 'Le mont Kemmel'],
    ['Qui a peint « L’Empire des lumières » ?', 'René Magritte', 'Paul Delvaux', 'James Ensor', 'Constant Permeke'],
    ['Quel fleuve traverse Liège ?', 'La Meuse', 'L’Escaut', 'La Sambre', 'La Senne'],
    ['Quel roi a succédé à Baudouin ?', 'Albert II', 'Philippe', 'Léopold III', 'Albert Ier'],
    ['En quelle année le roi Philippe a-t-il prêté serment ?', '2013', '2011', '2015', '2009'],
    ['Quelle ville abrite le plus grand port de Belgique ?', 'Anvers', 'Zeebruges', 'Gand', 'Ostende'],
    ['Qui a créé les Schtroumpfs ?', 'Peyo', 'Franquin', 'Morris', 'Hergé'],
    ['Qui a créé Lucky Luke ?', 'Morris', 'René Goscinny', 'Peyo', 'Albert Uderzo'],
    ['Qui a créé Gaston Lagaffe ?', 'André Franquin', 'Peyo', 'Jean Roba', 'Willy Vandersteen'],
    ['Quelle ville est le siège de la Communauté germanophone ?', 'Eupen', 'Saint-Vith', 'Malmedy', 'La Calamine'],
    ['Quel peintre a réalisé « L’Agneau mystique » avec son frère Hubert ?', 'Jan Van Eyck', 'Pieter Bruegel', 'Pierre Paul Rubens', 'Hans Memling'],
    ['Pour quelle exposition universelle l’Atomium a-t-il été construit ?', '1958', '1935', '1910', '1970'],
    ['Quel coureur belge était surnommé « le Cannibale » ?', 'Eddy Merckx', 'Rik Van Looy', 'Roger De Vlaeminck', 'Freddy Maertens'],
    ['Combien de Tours de France Eddy Merckx a-t-il gagnés ?', '5', '4', '6', '3'],
    ['Quel est le vrai nom de Stromae ?', 'Paul Van Haver', 'Paul Van Hove', 'Pierre Van Haver', 'Paul Vermeulen'],
    ['En quelle année a eu lieu la bataille de Waterloo ?', '1815', '1814', '1813', '1830'],
    ['Quel numéro appelle-t-on pour joindre directement la police en Belgique ?', '101', '100', '112', '105'],
    ['Quel organe contrôle de l’extérieur le fonctionnement des services de police ?', 'Le Comité P', 'Le Comité R', 'Le Conseil d’État', 'La Cour des comptes'],
    ['Depuis quelle année la Grand-Place de Bruxelles est-elle au patrimoine de l’UNESCO ?', '1998', '1985', '2005', '1992'],
    ['Quelle est la plus grande ville de Flandre ?', 'Anvers', 'Gand', 'Bruges', 'Louvain'],
    ['Combien de Régions compte la Belgique ?', '3', '2', '4', '5'],
    ['Quel fleuve traverse Anvers ?', 'L’Escaut', 'La Meuse', 'La Lys', 'La Dyle'],
    ['Quel écrivain liégeois a créé le commissaire Maigret ?', 'Georges Simenon', 'Jean Ray', 'Stanislas-André Steeman', 'Thomas Owen'],
    ['Quel écrivain belge, auteur de « L’Oiseau bleu », a reçu le prix Nobel de littérature ?', 'Maurice Maeterlinck', 'Émile Verhaeren', 'Georges Simenon', 'Michel de Ghelderode'],
    ['Qui est l’héritière du trône de Belgique ?', 'La princesse Élisabeth', 'La princesse Éléonore', 'La reine Mathilde', 'La princesse Astrid'],
    ['Quelle ville est célèbre pour son carnaval des Gilles ?', 'Binche', 'Malmedy', 'Alost', 'Eupen'],
    ['Quel Belge a conçu le World Wide Web avec Tim Berners-Lee ?', 'Robert Cailliau', 'Paul Otlet', 'Georges Lemaître', 'Ernest Solvay'],
    ['Quel prêtre et physicien belge a proposé l’« atome primitif », à l’origine du Big Bang ?', 'Georges Lemaître', 'Robert Cailliau', 'Ernest Solvay', 'Paul Otlet'],
    ['Que produit le procédé Solvay ?', 'Du carbonate de sodium', 'De l’acier', 'Du verre', 'De l’ammoniac'],
    ['Comment s’appelle le pendant féminin du Manneken-Pis ?', 'Jeanneke-Pis', 'Zinneke-Pis', 'Meisje-Pis', 'Mieke-Pis'],
    ['Quelle province a Arlon pour chef-lieu ?', 'Le Luxembourg', 'Namur', 'Liège', 'Le Hainaut'],
    ['Quel est le chef-lieu de la province de Hainaut ?', 'Mons', 'Charleroi', 'Tournai', 'La Louvière'],
    ['Quel est le chef-lieu du Brabant wallon ?', 'Wavre', 'Nivelles', 'Louvain-la-Neuve', 'Ottignies'],
    ['Quel est le chef-lieu du Limbourg ?', 'Hasselt', 'Genk', 'Tongres', 'Saint-Trond'],
    ['Dans la police intégrée, à quel cadre appartiennent les inspecteurs principaux ?', 'Le cadre moyen', 'Le cadre de base', 'Le cadre officier', 'Le cadre auxiliaire'],
    ['Dans quelle ville siège le Parlement de Wallonie ?', 'Namur', 'Liège', 'Mons', 'Charleroi'],
    ['Quelle ville est surnommée « la Venise du Nord » ?', 'Bruges', 'Gand', 'Malines', 'Anvers'],
    ['Quelle rivière traverse Charleroi ?', 'La Sambre', 'La Meuse', 'La Dendre', 'L’Escaut'],
    ['Qui chantait « Ne me quitte pas » ?', 'Jacques Brel', 'Salvatore Adamo', 'Arno', 'Maurane'],
    ['Quel peintre ostendais a peint « L’Entrée du Christ à Bruxelles » ?', 'James Ensor', 'René Magritte', 'Félicien Rops', 'Paul Delvaux'],
    ['Dans quelle ville se trouve le siège de l’OTAN ?', 'Bruxelles', 'Mons', 'Anvers', 'Liège'],
    ['Quel roi a régné pendant la Première Guerre mondiale ?', 'Albert Ier', 'Léopold II', 'Léopold III', 'Baudouin'],
    ['Combien de langues officielles compte la Belgique ?', '3', '2', '4', '1'],
  ],
};

// Ordre des thèmes dans la série du jour : 2 + 2 + 1, le thème « solo » tourne chaque jour.
const ORDRES = [['monde', 'sciences', 'belgique', 'monde', 'sciences'], ['sciences', 'belgique', 'monde', 'sciences', 'belgique'], ['belgique', 'monde', 'sciences', 'belgique', 'monde']];

/**
 * Série du jour d'un joueur : 5 questions { id, theme, q, choix: [4], bonne } (indice de la bonne réponse).
 * Sans répétition pendant une saison (chaque thème est parcouru dans un ordre propre au joueur).
 */
export function quizDuJour({ seed, uid, season, turn }) {
  const ordre = ORDRES[((turn % 3) + 3) % 3];
  const vus = { monde: 0, sciences: 0, belgique: 0 };
  // Questions déjà posées les tours précédents de la saison, par thème.
  for (let t = 1; t < turn; t++) for (const th of ORDRES[t % 3]) vus[th]++;
  const pris = { monde: 0, sciences: 0, belgique: 0 };
  return ordre.map((th, k) => {
    const banque = QUIZ_BANQUE[th];
    const melange = makeRng(`${seed}:quiz:${uid}:s${season}:${th}`).shuffle(banque.map((_, i) => i));
    const i = melange[(vus[th] + pris[th]++) % banque.length];
    const [q, bonne, ...leurres] = banque[i];
    const choix = makeRng(`${seed}:quiz:${uid}:s${season}:t${turn}:${k}`).shuffle([bonne, ...leurres]);
    return { id: `${th}-${i}`, theme: th, q, choix, bonne: choix.indexOf(bonne) };
  });
}
